name: Deploy to VM

on:
  push:
    branches: [ main ]  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Create app directory if it doesn't exist
            mkdir -p ~/mstr-app
            
            # Stop existing service if running
            sudo systemctl stop mstr-app || true
            
            # Clean existing files
            rm -rf ~/mstr-app/*
            
            # Copy new files
            cd ~/mstr-app
            
            # Start the service
            sudo systemctl start mstr-app
